[package]
name = "saladict-services"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
parking_lot.workspace = true
once_cell.workspace = true
saladict-core.workspace = true
saladict-net.workspace = true
saladict-platform.workspace = true
async-trait.workspace = true
reqwest.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
anyhow.workspace = true
hmac.workspace = true
sha1.workspace = true
sha2.workspace = true
md-5.workspace = true
hex.workspace = true
base64.workspace = true
image.workspace = true
rqrr.workspace = true
uuid.workspace = true
rand.workspace = true
chrono.workspace = true
urlencoding.workspace = true
tokio.workspace = true
futures.workspace = true
log.workspace = true

[lints]
workspace = true
